import { Request, Response } from 'express'
import { asyncHandler } from '@/middleware/errorHandler'
import { getSettings, updateSettings } from '@/models/settings'

export const getStoreSettings = asyncHandler(async (req: Request, res: Response) => {
  const settings = await getSettings()
  res.json({ success: true, data: settings })
})

export const createStoreSettings = asyncHandler(async (req: Request, res: Response) => {
  const {
    site_title,
    site_title_en,
    site_title_az,
    site_title_he,
    site_title_ru,
    header_title_en,
    header_title_az,
    header_title_he,
    header_title_ru,
    banner_title_en,
    banner_title_az,
    banner_title_he,
    banner_title_ru,
    banner_description_en,
    banner_description_az,
    banner_description_he,
    banner_description_ru,
    banner_url,
    banner_background_color,
    banner_background_image,
    top_description,
    address,
    phone,
    email,
    whatsapp,
    logo_url,
    tagline,
    favicon_url,
    primary_color,
    lang_label_en,
    lang_label_ru,
    lang_label_he,
  } = req.body

  // updateSettings handles both insert and update
  const created = await updateSettings({
    site_title,
    site_title_en,
    site_title_az,
    site_title_he,
    site_title_ru,
    header_title_en,
    header_title_az,
    header_title_he,
    header_title_ru,
    banner_title_en,
    banner_title_az,
    banner_title_he,
    banner_title_ru,
    banner_description_en,
    banner_description_az,
    banner_description_he,
    banner_description_ru,
    banner_url,
    banner_background_color,
    banner_background_image,
    top_description,
    address,
    phone,
    email,
    whatsapp,
    logo_url,
    tagline,
    favicon_url,
    primary_color,
    lang_label_en,
    lang_label_ru,
    lang_label_he,
  })

  res.json({ success: true, data: created })
})

export const updateStoreSettings = asyncHandler(async (req: Request, res: Response) => {
  const {
    site_title,
    site_title_en,
    site_title_az,
    site_title_he,
    site_title_ru,
    header_title_en,
    header_title_az,
    header_title_he,
    header_title_ru,
    banner_title_en,
    banner_title_az,
    banner_title_he,
    banner_title_ru,
    banner_description_en,
    banner_description_az,
    banner_description_he,
    banner_description_ru,
    banner_url,
    banner_background_color,
    banner_background_image,
    top_description,
    address,
    phone,
    email,
    whatsapp,
    logo_url,
    tagline,
    favicon_url,
    primary_color,
    lang_label_en,
    lang_label_ru,
    lang_label_he,
  } = req.body

  const updated = await updateSettings({
    site_title,
    site_title_en,
    site_title_az,
    site_title_he,
    site_title_ru,
    header_title_en,
    header_title_az,
    header_title_he,
    header_title_ru,
    banner_title_en,
    banner_title_az,
    banner_title_he,
    banner_title_ru,
    banner_description_en,
    banner_description_az,
    banner_description_he,
    banner_description_ru,
    banner_url,
    banner_background_color,
    banner_background_image,
    top_description,
    address,
    phone,
    email,
    whatsapp,
    logo_url,
    tagline,
    favicon_url,
    primary_color,
    lang_label_en,
    lang_label_ru,
    lang_label_he,
  })

  res.json({ success: true, data: updated })
})
